### ISSUE TITLE
The setDiffusionDataMultiQubit  function is missing 

### ISSUE THREAD

**Issue by ma893460966** [Francis-Hsu/QuantGenMdl#1]
This code is wrong, in file  QDDPM_phase :from src.QDDPM_jax import HaarSampleGeneration, QDDPM, setDiffusionDataMultiQubit .

The function setDiffusionDataMultiQubit is missing in QDDPM_jax. Expect the author to update the codebase.

**Comment by ma893460966** [comment]
My email address is quangongma@163.com, and I look forward to hearing from you

**Comment by bingzhi-Zhang365** [comment]
> This code is wrong, in file QDDPM_phase :from src.QDDPM_jax import HaarSampleGeneration, QDDPM, setDiffusionDataMultiQubit .
> 
> The function setDiffusionDataMultiQubit is missing in QDDPM_jax. Expect the author to update the codebase.

Sorry for the missing function, and it is now updated.

**Comment by ma893460966** [comment]
@bzGit06   In src.QDDPM_jax,  the defined function "setDiffusionDataMultiQubit“ still lacks the function "scrambleCircuitMultiQubit"

**Comment by ma893460966** [comment]
@bzGit06   In src.QDDPM_jax,  the defined function "setDiffusionDataMultiQubit“ still lacks the function "scrambleCircuitMultiQubit"

**Comment by ma893460966** [comment]
@bzGit06   In src.QDDPM_jax,  the defined function "setDiffusionDataMultiQubit“ still lacks the function "scrambleCircuitMultiQubit"

**Comment by ma893460966** [comment]
def setDiffusionDataMultiQubit(inputs, diff_hs, n):
    '''
    Obtain the quantum data set for multi qubit through diffusion step t
    Args:
    t: diffusion step
    inputs: the input quantum data set
    diff_hs: the hyper-parameter to control the amplitude of quantum circuit angles
    n: number of qubits
    '''
    t = diff_hs.shape[0]
    Ndata = inputs.shape[0]
    
    key = jax.random.PRNGKey(t)
    phis = jax.random.uniform(key, shape=(Ndata, 3 * n * t), minval=-jnp.pi/8., maxval=jnp.pi/8.)
    phis *= jnp.repeat(diff_hs, 3*n)

    gs = jax.random.uniform(key, shape=(Ndata, t), minval=0.4, maxval=0.6)
    gs *= diff_hs 

    states = K.vmap(partial(scrambleCircuitMultiQubit, n=n), vectorized_argnums=(0, 1, 2))(inputs, phis, gs)

    return states


 lacks the function "scrambleCircuitMultiQubit":states = K.vmap(partial(scrambleCircuitMultiQubit, n=n), vectorized_argnums=(0, 1, 2))(inputs, phis, gs)

**Comment by bingzhi-Zhang365** [comment]
> @bzGit06 In src.QDDPM_jax, the defined function "setDiffusionDataMultiQubit“ still lacks the function "scrambleCircuitMultiQubit"

Sorry for it. Now the "scrambleCircuitMultiQubit" function is updated.

**Comment by ma893460966** [comment]
@bzGit06 "from itertools import combinations" should be written to src.QDDPM_jax,  because there is code " for i, j in combinations(range(n), 2):"

**Comment by bingzhi-Zhang365** [comment]
> @bzGit06 "from itertools import combinations" should be written to src.QDDPM_jax, because there is code " for i, j in combinations(range(n), 2):"

Thank you for your suggestion.
